[package]
name = "async-await-echo"
version = "0.1.0"
authors = ["Taylor Cramer <cramertj@google.com>"]
edition = "2018"

[dependencies]
futures-preview = { version = "0.3.0-alpha.6", features = ["tokio-compat"] }
hyper = "0.12.9"
tokio-async-await = "0.1.0"
